source ~/.dotfiles/bash/aliases.sh
source ~/.dotfiles/bash/bash-completion.sh
source ~/.dotfiles/bash/colors.sh
source ~/.dotfiles/bash/config.sh
source ~/.dotfiles/bash/git-prompt.sh
source ~/.dotfiles/bash/env.sh
